version: '3.6'

services:

  app:
    build: .
    env_file:
      - .env
    volumes:
      - ./apache2/htdocs:/usr/local/apache2/htdocs
      - ./apache2/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./apache2/conf/conf.d:/usr/local/apache2/conf/conf.d
    ports:
      - 8080:80
