version: '3.6'

services:

  app:
    build: .
    env_file:
      - .env
    volumes:
      - ./httpd/html:/var/www/html
      - ./httpd/conf/httpd.conf:/etc/httpd/conf/httpd.conf
      - ./httpd/conf.d/php7.3.conf:/etc/httpd/conf.d/php7.3.conf
      - ./httpd/conf.d/mod_auth_openidc.conf:/etc/httpd/conf.d/mod_auth_openidc.conf
    ports:
      - 8080:80
